### ISSUE TITLE
Supporing InputEventJoypadMotion

### ISSUE THREAD

**Issue by kingoftheconnors** [PunchablePlushie/godot_ggs#11]
I have a controller whose left/right/up/down controls return a InputEventJoypadMotion event instead of an InputEventJoypadButton.

Horizontal movements have axis=0 and axis_value=1 for right (-1 for left).
Vertical movements have axis=1 and axis_value=1 for down (-1 for up).

Is there a way to make keybind_gp support this?

**Comment by PunchablePlushie** [comment]
Supporting gamepad sticks requires changing some stuff. It's essentially a new feature. I've created a new branch and changed some stuff that should (theoretically) work. But as we all know, the chance of the code actually working on the first try is -100%.

Unfortunately, my gamepad is broken so I can't test the feature myself. Someone else should go ahead and pull the `gp-axis-support` branch and test things out and maybe try to fix the potential bugs. Also, you can go ahead and head to [GGS-Demo repo](https://github.com/PunchablePlushie/GGS-Demo/tree/main). I pushed the changes over there too so whoever is going to test things out doesn't need to create a project from scratch. They can just use the GGS Demo (the Finished one) to test and debug things.

**Comment by kingoftheconnors** [comment]
I tested it out and made a few fixes, which I'll make a PR for. I'll be using the PR branch until it gets pulled in. Thank you for being so quick to respond!

**Comment by PunchablePlushie** [comment]
I merged the pull request. Things should be working fine now. I'll go ahead and update the rest of the stuff (version history, Asset Library version, wiki, etc) in a bit.
