### ISSUE TITLE
Components wiki page out of date

### ISSUE THREAD

**Issue by Kylogias** [PunchablePlushie/godot_ggs#6]
The components page on the wiki, in the Keybinds section (https://github.com/PunchablePlushie/godot_ggs/wiki/Components#keybind-components-keyboard-and-gamepad) is out of date. It needs to be edited to include references to the new mouse bind feature, for instance, adding how to find the mouse button index and where it says Keyboard and Gamepad, it should also say mouse. I can't find the edit button for the wiki so I'm posting this issue

**Comment by PunchablePlushie** [comment]
Thank you for reminding me that! The wiki got updated.
